### ISSUE TITLE
[Apple] return receipt for expired subscriptions

### ISSUE THREAD

**Issue by raduflp** [Wizcorp/node-iap#37] opened 2017-12-13 21:54 UTC
If the subscription has expired (21006), the response indeed contains a valid decoded receipt. 
I think it would make sense to return the decoded receipt rather than throwing an error. 
What do you guys think?

**Comment by ronkorving** [comment] 2017-12-15 06:12
I'm just one guy with an opinion, but to me that probably makes sense. I would still want to see some boolean that tells me "this has expired or not", which we may be able to stick on the root object that we return. Thoughts?

**Comment by gkye** [comment] 2017-12-18 18:09
+1 on adding an expiration boolean the root object

**Comment by superandrew213** [comment] 2018-03-18 00:37
@ronkorving couldn't you just check the expiry date yourself?

For Google purchases you would need to use the Google API to get the expiry date since google only provides the purchase date:
https://developers.google.com/android-publisher/api-ref/purchases/subscriptions/get

However I agree with @raduflp. Valid receipts should always be returned.

Maybe it's best to only validate and return receipt/transactions. The rest we should handle ourselves.

**Comment by ronkorving** [comment] 2018-03-19 03:36
@superandrew213 Sure, but different services may format dates differently. I think it would be nice if you didn't have to worry about that.

**Comment by superandrew213** [comment] 2018-03-19 06:53
@ronkorving true. Maybe I'm ok with how it is since I have my own wrapper around it that takes care of all that.

I switched over to `node-iap` from `in-app-purchase` since it had too much weird stuff going on and the code was a bit all over the place.

What do you think about adding more common fields? Eg.

```
{
  "platform": "apple",
  "productId": "abc",
  "transactionId": "120000233230473",
  "expirationDate" : xxx,
  "purchaseDate": xxx,
}
```

**Comment by ronkorving** [comment] 2018-03-19 07:02
@superandrew213 Good idea 👍 Anything that all/most platforms have in common, we could technically expose.

**Comment by KLVTZ** [comment] 2018-04-27 22:41
@superandrew213 yeah I like the idea of common fields. Right now we build the object after receiving the response so this would save us one extra line. 

```
        // Provide common interface back to request
        return {
            productId: responseFromApple.productId,
            platformReceiptId: subscription.receipt,
            expiration: maxExpireTime
        };
```

I think many fall into the same bucket of composing their own interface on top of this so its good to have some flexibility.

In regards to @raduflp, I must be misreading his issue, because it sounds like we don't return the receipt for an expired subscription? I just did a call with an old receipt, from a cancelled account from last year, and I'm still able to see their information. Maybe its not a subscription based receipt?

**Comment by superandrew213** [comment] 2018-04-28 00:14
@KLVTZ I think @raduflp is referring to this line here:
https://github.com/Wizcorp/node-iap/blob/master/lib/apple/index.js#L42

If we receive status code `21006`, we throw an error. Only status code 0 is passing through at the moment.

Did you maybe test with my [PR](https://github.com/Wizcorp/node-iap/pull/40)? I fixed this issue there. Maybe that is why you are getting the expired subscription receipt data.

**Comment by KLVTZ** [comment] 2018-04-28 01:54
@superandrew213 yeah haven't been able to reproduce it with your PR either. I think our subscription setup might be different than whats reported here. Either case, nice to see your PR supports it.

**Comment by justinpage** [comment] 2018-09-16 00:30
@ronkorving #40 supports `21006` responses. I think we can close this.

**Closed** 2018-09-19 01:53 UTC
